language: python
python:
  - 3.6
sudo: false
addons:
  apt:
    packages:
    - bc

install:
- eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

script:
- ln -s $(pwd)/vimrc ~/.vimrc
- ln -s $(pwd) ~/.vim
- cd ~/.vim
- ./manage install
